name: Publish wiki

on:
  push:
    branches:
      - main
    paths:
      - docs/wiki/**
      - .github/workflows/publish-wiki.yml
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Andrew-Chen-Wang/github-wiki-action@b7e552d7cb0fa7f83e459012ffc6840fd87bcb83
        with:
          path: docs/wiki/
